{% set name = "sid-dev" %}
{% set version = "0.0.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/s/sid_dev/sid_dev-{{ version }}.tar.gz
  sha256: 621d4f7c0d55a0c5d1c0c93ece9a883bbdd89f37c9733ba9f3b6de93616c05a5

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - bokeh
    - dask
    - fastparquet !=0.6.1
    - holoviews
    - matplotlib-base
    - numba >=0.48
    - numpy
    - pandas >=1
    - python >={{ python_min }}
    - python-snappy
    - seaborn
    - tqdm

test:
  imports:
    - sid
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/covid-19-impact-lab/sid
  summary: Simulate the spread of COVID-19 with different policies.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/covid-19-impact-lab/sid
  doc_url: https://sid-dev.readthedocs.io/

extra:
  recipe-maintainers:
    - tobiasraabe
    - roecla
    - janosg
